apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: pxbbq-prod
  labels:
    app: postgres
data:
  POSTGRES_DB: pxbbq
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: porxie
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: pxbbq-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: pxbbq-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: 'postgres:17'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgresdata
          livenessProbe:
            exec:
              command:
                - "pg_isready"
                - "-q"
                - "-U"
                - "postgres"
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: pxbbq-prod
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres
