# Create PXBBQ Namespace
---
apiVersion: v1
kind: Namespace                 
metadata:
  name: pxbbq
  labels:
    platform.portworx.com/pds: "true"
---
apiVersion: v1
kind: Namespace                 
metadata:
  name: development
  labels:
    platform.portworx.com/pds: "true"
